### ISSUE TITLE
Cannot find .pt file

### ISSUE THREAD

**Issue by ThisIsIt42** [IsoNet-cryoET/spIsoNet#10]
I use the following command : spisonet.py  reconstruct P76_J435_map_half_1.mrc P76_J435_map_half_2.mrc --aniso_file FSC3D.mrc --mask P76_J435mask.mrc --limit_res 3.2 --epochs 30 --alpha 1 --beta 0.5 --output_dir output_1 --gpuID B2,B3 --acc_batches 2 

and i get the following error : 

04-22 14:05:11, INFO     voxel_size 1.309999942779541
04-22 14:05:13, INFO     spIsoNet correction until resolution 3.2A!
                     Information beyond 3.2A remains unchanged
04-22 14:05:48, INFO     Start preparing subvolumes!
04-22 14:05:55, INFO     Done preparing subvolumes!
04-22 14:05:55, INFO     Start training!
04-22 14:05:57, INFO     Port number: 43493
learning rate 0.0003
['..P76_J435_map_half_1_data', '..P76_J435_map_half_2_data']
Traceback (most recent call last):
  File "/programs/x86_64-linux/spisonet/1.0_cu11.8/bin/spisonet.py", line 553, in <module>
    exit(main())
  File "/programs/x86_64-linux/spisonet/1.0_cu11.8/bin/spisonet.py", line 549, in main
    fire.Fire(ISONET)
  File "/programs/x86_64-linux/spisonet/1.0_cu11.8/mamba/lib/python3.10/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/programs/x86_64-linux/spisonet/1.0_cu11.8/mamba/lib/python3.10/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/programs/x86_64-linux/spisonet/1.0_cu11.8/mamba/lib/python3.10/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/programs/x86_64-linux/spisonet/1.0_cu11.8/bin/spisonet.py", line 182, in reconstruct
    map_refine_n2n(halfmap1,halfmap2, mask_vol, fsc3d, alpha = alpha,beta=beta,  voxel_size=voxel_size, output_dir=output_dir, 
  File "/programs/x86_64-linux/spisonet/1.0_cu11.8/spIsoNet/spIsoNet/bin/map_refine.py", line 145, in map_refine_n2n
    network.train([data_dir_1,data_dir_2], output_dir, alpha=alpha,beta=beta, output_base=output_base0, batch_size=batch_size, epochs = epochs, steps_per_epoch = 1000, 
  File "/programs/x86_64-linux/spisonet/1.0_cu11.8/spIsoNet/spIsoNet/models/network_n2n.py", line 273, in train
    checkpoint = torch.load(model_path)
  File "/programs/x86_64-linux/spisonet/1.0_cu11.8/mamba/lib/python3.10/site-packages/torch/serialization.py", line 998, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/programs/x86_64-linux/spisonet/1.0_cu11.8/mamba/lib/python3.10/site-packages/torch/serialization.py", line 445, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/programs/x86_64-linux/spisonet/1.0_cu11.8/mamba/lib/python3.10/site-packages/torch/serialization.py", line 426, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '..output_1/P76_J435_map_half_.pt

any idea what the issue is ?

**Comment by procyontao** [comment]
Hi,

This could be a bug in spIsoNet related to the name of output folder.
How about changing "--output_dir output_1 " to  "--output_dir output1", or without specify "--output_dir"?

**Comment by ThisIsIt42** [comment]
$ spisonet.py  reconstruct P76_J435_map_half_1.mrc P76_J435_map_half_2.mrc --aniso_file FSC3D.mrc --mask P76_J435mask.mrc --limit_res 3.2 --epochs 30 --alpha 1 --beta 0.5 --gpuID B2,B3 --acc_batches 2
04-22 15:22:00, INFO     voxel_size 1.309999942779541
04-22 15:22:02, INFO     spIsoNet correction until resolution 3.2A!
                     Information beyond 3.2A remains unchanged
04-22 15:22:37, INFO     Start preparing subvolumes!
04-22 15:22:42, INFO     Done preparing subvolumes!
04-22 15:22:42, INFO     Start training!
04-22 15:22:44, INFO     Port number: 40421
learning rate 0.0003
['isonet_maps/P76_J435_map_half_1_data', 'isonet_maps/P76_J435_map_half_2_data']
Traceback (most recent call last):
  File "/programs/x86_64-linux/spisonet/1.0_cu11.8/bin/spisonet.py", line 553, in <module>
    exit(main())
  File "/programs/x86_64-linux/spisonet/1.0_cu11.8/bin/spisonet.py", line 549, in main
    fire.Fire(ISONET)
  File "/programs/x86_64-linux/spisonet/1.0_cu11.8/mamba/lib/python3.10/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/programs/x86_64-linux/spisonet/1.0_cu11.8/mamba/lib/python3.10/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/programs/x86_64-linux/spisonet/1.0_cu11.8/mamba/lib/python3.10/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/programs/x86_64-linux/spisonet/1.0_cu11.8/bin/spisonet.py", line 182, in reconstruct
    map_refine_n2n(halfmap1,halfmap2, mask_vol, fsc3d, alpha = alpha,beta=beta,  voxel_size=voxel_size, output_dir=output_dir, 
  File "/programs/x86_64-linux/spisonet/1.0_cu11.8/spIsoNet/spIsoNet/bin/map_refine.py", line 145, in map_refine_n2n
    network.train([data_dir_1,data_dir_2], output_dir, alpha=alpha,beta=beta, output_base=output_base0, batch_size=batch_size, epochs = epochs, steps_per_epoch = 1000, 
  File "/programs/x86_64-linux/spisonet/1.0_cu11.8/spIsoNet/spIsoNet/models/network_n2n.py", line 273, in train
    checkpoint = torch.load(model_path)
  File "/programs/x86_64-linux/spisonet/1.0_cu11.8/mamba/lib/python3.10/site-packages/torch/serialization.py", line 998, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/programs/x86_64-linux/spisonet/1.0_cu11.8/mamba/lib/python3.10/site-packages/torch/serialization.py", line 445, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/programs/x86_64-linux/spisonet/1.0_cu11.8/mamba/lib/python3.10/site-packages/torch/serialization.py", line 426, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'isonet_maps/P76_J435_map_half_.pt'
[da497@cbsucryoem01 InputData_01]$ 

So I tried both suggestions and receive the same error

**Comment by ThisIsIt42** [comment]
$ spisonet.py  reconstruct P76_J435_map_half_1.mrc P76_J435_map_half_2.mrc --aniso_file FSC3D.mrc --mask P76_J435mask.mrc --limit_res 3.2 --epochs 30 --alpha 1 --beta 0.5 --gpuID B2,B3 --acc_batches 2
04-22 15:22:00, INFO     voxel_size 1.309999942779541
04-22 15:22:02, INFO     spIsoNet correction until resolution 3.2A!
                     Information beyond 3.2A remains unchanged
04-22 15:22:37, INFO     Start preparing subvolumes!
04-22 15:22:42, INFO     Done preparing subvolumes!
04-22 15:22:42, INFO     Start training!
04-22 15:22:44, INFO     Port number: 40421
learning rate 0.0003
['isonet_maps/P76_J435_map_half_1_data', 'isonet_maps/P76_J435_map_half_2_data']
Traceback (most recent call last):
  File "/programs/x86_64-linux/spisonet/1.0_cu11.8/bin/spisonet.py", line 553, in <module>
    exit(main())
  File "/programs/x86_64-linux/spisonet/1.0_cu11.8/bin/spisonet.py", line 549, in main
    fire.Fire(ISONET)
  File "/programs/x86_64-linux/spisonet/1.0_cu11.8/mamba/lib/python3.10/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/programs/x86_64-linux/spisonet/1.0_cu11.8/mamba/lib/python3.10/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/programs/x86_64-linux/spisonet/1.0_cu11.8/mamba/lib/python3.10/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/programs/x86_64-linux/spisonet/1.0_cu11.8/bin/spisonet.py", line 182, in reconstruct
    map_refine_n2n(halfmap1,halfmap2, mask_vol, fsc3d, alpha = alpha,beta=beta,  voxel_size=voxel_size, output_dir=output_dir, 
  File "/programs/x86_64-linux/spisonet/1.0_cu11.8/spIsoNet/spIsoNet/bin/map_refine.py", line 145, in map_refine_n2n
    network.train([data_dir_1,data_dir_2], output_dir, alpha=alpha,beta=beta, output_base=output_base0, batch_size=batch_size, epochs = epochs, steps_per_epoch = 1000, 
  File "/programs/x86_64-linux/spisonet/1.0_cu11.8/spIsoNet/spIsoNet/models/network_n2n.py", line 273, in train
    checkpoint = torch.load(model_path)
  File "/programs/x86_64-linux/spisonet/1.0_cu11.8/mamba/lib/python3.10/site-packages/torch/serialization.py", line 998, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/programs/x86_64-linux/spisonet/1.0_cu11.8/mamba/lib/python3.10/site-packages/torch/serialization.py", line 445, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/programs/x86_64-linux/spisonet/1.0_cu11.8/mamba/lib/python3.10/site-packages/torch/serialization.py", line 426, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'isonet_maps/P76_J435_map_half_.pt'
[ InputData_01]$ 

So I tried both suggestions and receive the same error

**Comment by procyontao** [comment]
Hi,

I would like to ask what does it means by "--gpuID B2,B3", usually the "--gpuID" should be 0,1 or 0,1,2,3, or without specifying it to use all available gpus.

**Comment by ThisIsIt42** [comment]
So intially when I ran with GPU ids 0,1,2 i would get an error saying : Triton Error [CUDA]: device kernel image is invalid. So i found the ids of the gpus.

**Comment by ThisIsIt42** [comment]
So i removed the gpu flag and i got an output port but the run failed. I checked our cuda version and it seems to be 11.2 would this be the cause of the failure to run ?

**Comment by procyontao** [comment]
The cuda version need to match the pytorch version and the Nvidia driver. 
Probably you want to choose an old version of pytorch? https://pytorch.org/get-started/previous-versions/

**Comment by flng000** [comment]
Hi, I have the same troubles (Triton Error [CUDA]: device kernel image is invalid). Which version of pytorch would you recommend?
Thanks and all the best

**Comment by shl4014** [comment]
I also got the same error as ThisIsIt42, and tried removing the output_dir flag and gpu flag, but this did not help.
Are there any more ideas how to solve this issue?
Thanks!
Shifra

**Comment by angela31398** [comment]
Hi! 
I have problems with the following command: 
>>> spisonet.py reconstruct mapA006.mrc mapB006.mrc --aniso_file FSC3D.mrc --mask mask.mrc --limit_res 3.2 --epochs 30 --alpha 1 --beta 0.5 --output_dir ouput1  isonet_maps --gpuID 0,1,2,3 --acc_batches 2 

And I obtain the following error: 
12-02 11:55:25, INFO     requested number of cpus is more than the number of the cpu cores in the system
12-02 11:55:25, INFO     setting ncpus to 12
12-02 11:55:25, INFO     voxel_size 0.8238000273704529
12-02 11:55:26, INFO     processing half1
12-02 11:55:26, INFO     spIsoNet correction until resolution 3.2A!
                     Information beyond 3.2A remains unchanged
12-02 11:55:28, INFO     Start preparing subvolumes!
12-02 11:55:30, INFO     Done preparing subvolumes!
12-02 11:55:30, INFO     Start training!
/home/angela/anaconda3/envs/spisonet/lib/python3.10/site-packages/torch/cuda/__init__.py:716: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")
12-02 11:55:31, INFO     Port number: 34307
learning rate 0.0003
/home/angela/anaconda3/envs/spisonet/lib/python3.10/site-packages/spIsoNet/models/network.py:244: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(model_path)
Traceback (most recent call last):
  File "/home/angela/anaconda3/envs/spisonet/bin/spisonet.py", line 8, in <module>
    sys.exit(main())
  File "/home/angela/anaconda3/envs/spisonet/lib/python3.10/site-packages/spIsoNet/bin/spisonet.py", line 549, in main
    fire.Fire(ISONET)
  File "/home/angela/anaconda3/envs/spisonet/lib/python3.10/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/angela/anaconda3/envs/spisonet/lib/python3.10/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/angela/anaconda3/envs/spisonet/lib/python3.10/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/angela/anaconda3/envs/spisonet/lib/python3.10/site-packages/spIsoNet/bin/spisonet.py", line 171, in reconstruct
    map_refine(halfmap1, mask_vol, fsc3d, alpha = alpha,  voxel_size=voxel_size, output_dir=output_dir, 
  File "/home/angela/anaconda3/envs/spisonet/lib/python3.10/site-packages/spIsoNet/bin/map_refine.py", line 63, in map_refine
    network.train(data_dir, output_dir, alpha=alpha, output_base=output_base, batch_size=batch_size, epochs = epochs, steps_per_epoch = 1000, 
  File "/home/angela/anaconda3/envs/spisonet/lib/python3.10/site-packages/spIsoNet/models/network.py", line 244, in train
    checkpoint = torch.load(model_path)
  File "/home/angela/anaconda3/envs/spisonet/lib/python3.10/site-packages/torch/serialization.py", line 1319, in load
    with _open_file_like(f, "rb") as opened_file:
  File "/home/angela/anaconda3/envs/spisonet/lib/python3.10/site-packages/torch/serialization.py", line 659, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/angela/anaconda3/envs/spisonet/lib/python3.10/site-packages/torch/serialization.py", line 640, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'ouput1/mapA006.pt'
(spisonet) 

I have try to put easy names for my .mrc, and  change "--output_dir output_1 " to "--output_dir output1", or without specify "--output_dir"?

I don't know what is the archive "XX.pt", and I don't know if is something that I have to have when I installed the program, or if is generate during the program is running. Moreover I have try with the example and I have the same problem. And I thought that it was something related with the folder isonet_maps but apparently it is empty. 

Thanks in advance!

**Comment by hanyunlqq-lab** [comment]
I've also encountered this problem. Has it been resolved now？
