### ISSUE TITLE
BlockingIOError: [Errno 11] Resource temporarily unavailable

### ISSUE THREAD

**Issue by ChobitParrotBioC** [IsoNet-cryoET/spIsoNet#7]
Hi,

I installed the package using option 1.

Then I run and got this error:
04-17 11:31:02, INFO     voxel_size 1.0800000429153442
04-17 11:31:05, INFO     spIsoNet correction until resolution 3.4A!
                     Information beyond 3.4A remains unchanged
04-17 11:31:15, INFO     Start preparing subvolumes!
Traceback (most recent call last):
  File "/home/spuser/anaconda3/envs/spisonet/bin/spisonet.py", line 8, in <module>
    sys.exit(main())
  File "/home/spuser/anaconda3/envs/spisonet/lib/python3.10/site-packages/spIsoNet/bin/spisonet.py", line 549, in main
    fire.Fire(ISONET)
  File "/home/spuser/anaconda3/envs/spisonet/lib/python3.10/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/spuser/anaconda3/envs/spisonet/lib/python3.10/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/spuser/anaconda3/envs/spisonet/lib/python3.10/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/spuser/anaconda3/envs/spisonet/lib/python3.10/site-packages/spIsoNet/bin/spisonet.py", line 182, in reconstruct
    map_refine_n2n(halfmap1,halfmap2, mask_vol, fsc3d, alpha = alpha,beta=beta,  voxel_size=voxel_size, output_dir=output_dir, 
  File "/home/spuser/anaconda3/envs/spisonet/lib/python3.10/site-packages/spIsoNet/bin/map_refine.py", line 119, in map_refine_n2n
    extract_subvolume(halfmap1, seeds, cube_size, data_dir_1)
  File "/home/spuser/anaconda3/envs/spisonet/lib/python3.10/site-packages/spIsoNet/bin/map_refine.py", line 28, in extract_subvolume
    with mrcfile.new(im_name, overwrite=True) as output_mrc:
  File "/home/spuser/anaconda3/envs/spisonet/lib/python3.10/site-packages/mrcfile/mrcinterpreter.py", line 137, in __exit__
    self.close()
  File "/home/spuser/anaconda3/envs/spisonet/lib/python3.10/site-packages/mrcfile/mrcfile.py", line 163, in close
    super(MrcFile, self).close()
  File "/home/spuser/anaconda3/envs/spisonet/lib/python3.10/site-packages/mrcfile/mrcinterpreter.py", line 364, in close
    self.flush()
  File "/home/spuser/anaconda3/envs/spisonet/lib/python3.10/site-packages/mrcfile/mrcinterpreter.py", line 383, in flush
    self._iostream.truncate()
BlockingIOError: [Errno 11] Resource temporarily unavailable

Could you help me on this?
Thank you!

**Comment by procyontao** [comment]
Hi,
This is probably caused by unable to write to a folder (or disk). Whether any files or folders are generated?

**Comment by ChobitParrotBioC** [comment]
> Hi, This is probably caused by unable to write to a folder (or disk). Whether any files or folders are generated?

Thank you for your reply! it is the folder issue, after I move the file to a different location, the run can complete.
